swagger: '2.0'
info:
  description: First API specifications.
  version: '1.0'
  title: AMT Account Manager
host: localhost:8080
basePath: /api
schemes:
  - http

paths:
  /authentication:
    post:
      description: Authenticate a user.
      operationId: authenticateUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: credentials
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserCredentials'
      responses:
        '200':
          description: success
          schema:
            type: string
          headers:
            X-Expires-After:
              type: string
              format: date-time
              description: date in UTC when token expires
        400:
          description: Invalid email/password supplied.

  /users:
    post:
      description: Add a new user account.
      operationId: addUser
      consumes:
        - application/json
      parameters:
        - name: Authorization
          in: header
          type: string
          required: true
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: created
          schema:
            type: object

  /users/{email}:
    patch:
      description: Update the password of an existing user account.
      operationId: updateUser
      consumes:
        - application/json
      parameters:
        - name: Authorization
          in: header
          type: string
          required: true
        - name: email
          in: path
          required: true
          type: string
        - name: password
          in: body
          required: true
          schema:
            type: string
      responses:
        404:
          description: User not found.

definitions:
  User:
    type: object
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
      role:
        type: string

  UserCredentials:
    type: object
    properties:
      email:
        type: string
      password:
        type: string