swagger: '2.0'
info:
  description: First API specifications.
  version: '1.0'
  title: AMT Account Manager
host: localhost:8080
basePath: /api
schemes:
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

paths:
  /authentication:
    post:
      description: Authenticate a user.
      operationId: authenticateUser
      consumes:
        - application/json
      parameters:
        - name: credentials
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserCredentials'
      responses:
        200:
          description: success
          schema:
            description: JWT Token
            type: string
        400:
          description: Invalid email/password supplied.

  /users:
    post:
      security:
        - Bearer: []
      description: Add a new user account.
      operationId: addUser
      consumes:
        - application/json
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        201:
          description: created
        401:
          description: Invalid token
        403:
          description: Not an administrator
        409:
          description: User already exist


  /users/{email}:
    patch:
      security:
        - Bearer: []
      description: Update the password of an existing user account.
      operationId: updateUser
      consumes:
        - application/json
      parameters:
        - name: email
          in: path
          required: true
          type: string
        - name: password
          in: body
          required: true
          schema:
            type: object
            properties:
              password:
                type: string
      responses:
        201:
          description: User updated successfully
        401:
          description: Invalid token
        403:
          description: Update not allowed
        404:
          description: User not found.

definitions:
  User:
    type: object
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
      role:
        type: string

  UserCredentials:
    type: object
    properties:
      email:
        type: string
      password:
        type: string