INSERT INTO public."user_entity"(mail, first_name, last_name, password, role) VALUES
('yjqhxvzbqxhcgr', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('cnsszsphpnyfys', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('ficxvbddvpbqnz', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('zwzzqgbxixaybe', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('smcnofroaalvmu', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('twnsshexsxooqr', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('llhkcplcgikrom', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('lzwbiiepzfmbde', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('xzsceokkbakdfo', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('ivmtjsmcfyruwb', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator');INSERT INTO public."user_entity"(mail, first_name, last_name, password, role) VALUES
('yjqhxvzbqxhcgr', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('cnsszsphpnyfys', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('ficxvbddvpbqnz', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('zwzzqgbxixaybe', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('smcnofroaalvmu', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('twnsshexsxooqr', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('llhkcplcgikrom', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('lzwbiiepzfmbde', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('xzsceokkbakdfo', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('ivmtjsmcfyruwb', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator');INSERT INTO public."user_entity"(mail, first_name, last_name, password, role) VALUES
('yjqhxvzbqxhcgr', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('cnsszsphpnyfys', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('ficxvbddvpbqnz', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('zwzzqgbxixaybe', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('smcnofroaalvmu', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('twnsshexsxooqr', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('llhkcplcgikrom', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('lzwbiiepzfmbde', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('xzsceokkbakdfo', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('ivmtjsmcfyruwb', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator');INSERT INTO public."user_entity"(mail, first_name, last_name, password, role) VALUES
('yjqhxvzbqxhcgr', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('cnsszsphpnyfys', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('ficxvbddvpbqnz', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('zwzzqgbxixaybe', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('smcnofroaalvmu', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('twnsshexsxooqr', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('llhkcplcgikrom', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('lzwbiiepzfmbde', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('xzsceokkbakdfo', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('ivmtjsmcfyruwb', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator');INSERT INTO public."user_entity"(mail, first_name, last_name, password, role) VALUES
('yjqhxvzbqxhcgr', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('cnsszsphpnyfys', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('ficxvbddvpbqnz', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('zwzzqgbxixaybe', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('smcnofroaalvmu', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('twnsshexsxooqr', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('llhkcplcgikrom', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('lzwbiiepzfmbde', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('xzsceokkbakdfo', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('ivmtjsmcfyruwb', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator');INSERT INTO public."user_entity"(mail, first_name, last_name, password, role) VALUES
('yjqhxvzbqxhcgr', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('cnsszsphpnyfys', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('ficxvbddvpbqnz', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('zwzzqgbxixaybe', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('smcnofroaalvmu', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('twnsshexsxooqr', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('llhkcplcgikrom', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('lzwbiiepzfmbde', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator'),
('xzsceokkbakdfo', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Administrator'),
('ivmtjsmcfyruwb', 'FirstName', 'LastName', '$2a$10$bYNdFSjjeQZx7miuM9/AoeCpcKJCTaBczBD8NkQ57peAdNPkOeywC', 'Collaborator');